services:
  - type: web
    name: esp32-camera-receptor
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DEVICE_TOKEN
        generateValue: true
